version: "3.8"

services:
  app:
    build:
      context: .
      target: prod
    environment:
      - POSTGRES_DB=${POSTGRES_DB:?}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?}
      - POSTGRES_USER=${POSTGRES_USER:?}
    depends_on:
      - db
    ports:
      - "5000:8000"

  db:
    # https://github.com/docker-library/docs/blob/master/postgres/README.md
    image: postgres:15
    environment:
      - POSTGRES_DB=${POSTGRES_DB:?}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?}
      - POSTGRES_USER=${POSTGRES_USER:?}
    expose:
      - "5432"
    restart: always
    volumes:
      - type: volume
        source: db
        target: /var/lib/postgresql/data

  dbadmin:
    # https://www.pgadmin.org/docs/pgadmin4/latest/container_deployment.html
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL:?}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD:?}
    depends_on:
      - db
    ports:
      - "5433:80"
    restart: always
    volumes:
      - type: volume
        source: dbadmin
        target: /var/lib/pgadmin

volumes:
  db:
  dbadmin:
